---
# Sigul Server Variables
sigul_type: server
sigul_server_cert_nickname: "sigul-server"
sigul_nss_dir: /etc/pki/tls/sigul
sigul_bridge_name: "sigul-bridge.rockylinux.org"

# ipa-getcert variables
getcert_name: "{{ ansible_fqdn }}"
getcert_owner: sigul
getcert_nss_db_dir: "{{ sigul_nss_dir }}"
getcert_nss_nickname: "{{ sigul_bridge_cert_nickname }}"
getcert_nss: true
