---

roles:
  - name: geerlingguy.mysql
  # monitoring
  - name: cloudalchemy.node_exporter
  - name: cloudalchemy.prometheus
  - name: cloudalchemy.alertmanager
  - name: cloudalchemy.grafana
  - name: geerlingguy.gitlab
  - name: geerlingguy.postgresql
  - name: geerlingguy.php
  - name: geerlingguy.nodejs
  - name: geerlingguy.certbot
  - name: riemers.gitlab-runner


  - name: rockylinux.ipagetcert
    src: https://github.com/rocky-linux/ansible-role-ipa-getcert
    version: main
  - name: rockylinux.ipsilon
    src: https://github.com/rocky-linux/ansible-role-ipsilon
    version: main
  - name: rockylinux.kojihub
    src: https://github.com/rocky-linux/ansible-role-kojihub
    version: main
  - name: rockylinux.kojid
    src: https://github.com/rocky-linux/ansible-role-kojid
    version: main
  - name: rockylinux.rabbitmq
    src: https://github.com/rocky-linux/ansible-role-rabbitmq
    version: main
  - name: rockylinux.sigul
    src: https://github.com/rocky-linux/ansible-role-sigul
    version: main
  - name: rockylinux.matterbridge
    src: https://github.com/NeilHanlon/ansible-role-matterbridge
    version: master
  - name: rockylinux.pinnwand
    src: https://github.com/rocky-linux/ansible-role-pinnwand
    version: main
  - name: rockylinux.wikijs
    src: https://git.rockylinux.org/infrastructure/public/ansible/ansible-role-wikijs.git
    scm: git
    version: develop
...
