---

roles:
  - name: geerlingguy.mysql
  # monitoring
  - name: cloudalchemy.node-exporter
  - name: cloudalchemy.prometheus
  - name: geerlingguy.gitlab
  - name: geerlingguy.postgresql
  - name: rockylinux.ipagetcert
    src: https://github.com/rocky-linux/ansible-role-ipa-getcert
    version: main
  - name: rockylinux.ipsilon
    src: https://github.com/rocky-linux/ansible-role-ipsilon
    version: main
  - name: rockylinux.kojihub
    src: https://github.com/rocky-linux/ansible-role-kojihub
    version: main
  - name: rockylinux.mqtt
    src: https://github.com/rocky-linux/ansible-role-mqtt
    version: main

collections:
  # freeipa
  - name: freeipa.ansible_freeipa
    version: 0.3.1
  - name: community.general
  - name: community.mysql
  - name: community.rabbitmq
  - name: ansible.posix
  - name: ktdreyer.koji_ansible
