---
- name: restart_ssh
  service:
    name: sshd
    state: restarted

- name: restart_httpd
  service:
    name: httpd
    state: restarted

- name: reload_networkmanager
  service:
    name: NetworkManager
    state: reloaded

- name: regenerate_auditd_rules
  command: /sbin/augenrules

- name: restart_auditd
  service:
    name: auditd
    state: restarted
