---
# This playbook is meant to be used with callable variables, like adhoc or AWX.
# What: Creates groups in the idm infrastructure based on the variables provided

- name: Create our initial users
  hosts: ipaserver
  become: false
  gather_facts: false
  vars_files:
  - vars/vaults/encpass.yml

  tasks:
    - name: "Checking for user variables"
      assert:
        that:
          - ipaadmin_password | mandatory
          - ipa_group | mandatory
          - ipa_description | mandatory
          - ipa_posix | mandatory
        success_msg: "Required variables provided"
        fail_msg: "We are missing group information or ipa admin password"

    - name: "Creating Mandatory Groups"
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ ipa_group }}"
        description: "{{ ipa_description }}"
        nonposix: "{{ ipa_posix }}"
      tags:
        - groups
