---
# Installs ipsilon for basic SSO services
- name: Install and configure ipsilon server
  hosts: ipsilon
  become: true
  vars_files:
    - vars/encpass.yml

  # This is to try to avoid the handler issue in pre/post tasks
  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        msg: "/etc/no-ansible exists - skipping run on this node"

  # For now, this is sufficient for testing with a localhost cert. In the
  # future we will come up with a way to issue either an internal cert with a
  # front-facing externally signed cert, or just external altogether.
  roles:
    - role: rockylinux.ipsilon

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
