---
# Configures an instance to function as a HTTP serving member of repopool
- name: Configure Repo Pool hosts
  hosts: repopool
  become: true
  vars_files:
  - vars/vaults/encpass.yml
  - vars/common.yml
  - vars/mounts/repopool.yml

  # This is to try to avoid the handler issue in pre/post tasks
  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

  tasks:
    - name: "Setup shared filesystem mount"
      include_tasks: tasks/efs_mount.yml
      with_items: "{{ mounts }}"
      tags: ["koji_efs_mount"]

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
...
