---
# Creates the first set of groups for the IdM Infrastructure
- name: "Creating Mandatory Groups"
  ipagroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ item.group }}"
    description: "{{ item.description }}"
    nonposix: no
  loop: "{{ ipagroups }}"
  tags:
    - groups

