---
- name: "Creating Initial Accounts"
  ipauser:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ item.name }}"
    first: "{{ item.first }}"
    last: "{{ item.last }}"
    email: "{{ item.email }}"
    password: "{{ item.password }}"
    title: "{{ item.title }}"
    loginshell: "{{ item.loginshell }}"
    update_password: on_create
  loop: "{{ users }}"
  tags:
    - users

