---
# This builds out the initial users and groups for the rocky linux infra
- name: Create our initial users
  hosts: ipaserver
  become: false
  vars_files:
  - vars/encpass.yml

  tasks:
    - name: "Checking for user variables"
      assert:
        that:
          - ipaadmin_password | mandatory
        success_msg: "Required variables provided"
        fail_msg: "We are missing ipa admin password"

    - name: "Start users"
      ipadnszone:
        ipaadmin_password: '{{ ipaadmin_password }}'
        name: '{{ internal_domain }}'
      with_items:
        - dev.rockylinux.org
