---
# Creates the first server for an IPA infrastructure
# Variables for the infrastructure are in inventory/ipainventory
- name: Configure IPA server
  hosts: ipaserver
  become: true
  vars_files:
  - vars/encpass.yml

  roles:
  - role: ipaserver
    state: present

