---
x-efs_fs_opts_common: &common_fs_opts
  fstype: efs
  fsopts:
    - _netdev
    - tls
    - iam
    - rw

mounts:
  - name: prod-build-repos-staging
    <<: *common_fs_opts
    fsid: fs-XXXXXXXX
    mount_point: /mnt/repos-staging
    ip_map:
      us-east-2a: 10.101.100.249
      us-east-2b: 10.101.101.249
      us-east-2c: 10.101.102.249
  - name: prod-build-repos-production
    <<: *common_fs_opts
    fsid: fs-YYYYYYYY
    mount_point: /mnt/repos-production
    ip_map:
      us-east-2a: 10.101.100.246
      us-east-2b: 10.101.101.246
      us-east-2c: 10.101.102.246
